/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERVIZIO_H_RPCGEN
#define _SERVIZIO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Filename {
	char name[256];
};
typedef struct Filename Filename;

struct Input1 {
	char nome[256];
	char linea[256];
};
typedef struct Input1 Input1;

struct Input2 {
	char direttorio[256];
	char prefix[8];
};
typedef struct Input2 Input2;

struct Output {
	int n_files;
	Filename files[6];
};
typedef struct Output Output;

#define SERVIZIOPROG 0x20000015
#define SERVIZIOVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CONTA_OCCORRENZE_LINEA 1
extern  int * conta_occorrenze_linea_1(Input1 *, CLIENT *);
extern  int * conta_occorrenze_linea_1_svc(Input1 *, struct svc_req *);
#define LISTA_FILE_PREFISSO 2
extern  Output * lista_file_prefisso_1(Input2 *, CLIENT *);
extern  Output * lista_file_prefisso_1_svc(Input2 *, struct svc_req *);
extern int servizioprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CONTA_OCCORRENZE_LINEA 1
extern  int * conta_occorrenze_linea_1();
extern  int * conta_occorrenze_linea_1_svc();
#define LISTA_FILE_PREFISSO 2
extern  Output * lista_file_prefisso_1();
extern  Output * lista_file_prefisso_1_svc();
extern int servizioprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Filename (XDR *, Filename*);
extern  bool_t xdr_Input1 (XDR *, Input1*);
extern  bool_t xdr_Input2 (XDR *, Input2*);
extern  bool_t xdr_Output (XDR *, Output*);

#else /* K&R C */
extern bool_t xdr_Filename ();
extern bool_t xdr_Input1 ();
extern bool_t xdr_Input2 ();
extern bool_t xdr_Output ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SERVIZIO_H_RPCGEN */
