/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_XFILE_H_RPCGEN
#define _RPC_XFILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Filename {
	char name[256];
};
typedef struct Filename Filename;

struct Output {
	int n_files;
	Filename files[6];
};
typedef struct Output Output;

#define XFILEPROG 0x20000015
#define XFILEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ELIMINA_OCCORRENZE 1
extern  int * elimina_occorrenze_1(Filename *, CLIENT *);
extern  int * elimina_occorrenze_1_svc(Filename *, struct svc_req *);
#define LISTA_FILETESTO 2
extern  Output * lista_filetesto_1(Filename *, CLIENT *);
extern  Output * lista_filetesto_1_svc(Filename *, struct svc_req *);
extern int xfileprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ELIMINA_OCCORRENZE 1
extern  int * elimina_occorrenze_1();
extern  int * elimina_occorrenze_1_svc();
#define LISTA_FILETESTO 2
extern  Output * lista_filetesto_1();
extern  Output * lista_filetesto_1_svc();
extern int xfileprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Filename (XDR *, Filename*);
extern  bool_t xdr_Output (XDR *, Output*);

#else /* K&R C */
extern bool_t xdr_Filename ();
extern bool_t xdr_Output ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_XFILE_H_RPCGEN */
