/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RPC_xFile.h"

bool_t
xdr_Filename (XDR *xdrs, Filename *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->name, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Output (XDR *xdrs, Output *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->n_files))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->files, 6,
		sizeof (Filename), (xdrproc_t) xdr_Filename))
		 return FALSE;
	return TRUE;
}
