/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RPC_xFile.h"

bool_t
xdr_Input (XDR *xdrs, Input *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->direttorio, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->carattere))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->occorrenze))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_FileName (XDR *xdrs, FileName *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->fileName, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_OutputFileList (XDR *xdrs, OutputFileList *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->numeroFiles))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->files, 6,
		sizeof (FileName), (xdrproc_t) xdr_FileName))
		 return FALSE;
	return TRUE;
}
