/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_XFILE_H_RPCGEN
#define _RPC_XFILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Input {
	char direttorio[256];
	char carattere;
	int occorrenze;
};
typedef struct Input Input;

struct FileName {
	char name[256];
};
typedef struct FileName FileName;

struct OutputFileList {
	int numeroFiles;
	FileName files[6];
};
typedef struct OutputFileList OutputFileList;

#define FILEPROG 0x20000015
#define FILEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ELIMINA_OCCORRENZE 1
extern  int * elimina_occorrenze_1(FileName *, CLIENT *);
extern  int * elimina_occorrenze_1_svc(FileName *, struct svc_req *);
#define LISTA_FILE_CARATTERE 2
extern  OutputFileList * lista_file_carattere_1(Input *, CLIENT *);
extern  OutputFileList * lista_file_carattere_1_svc(Input *, struct svc_req *);
extern int fileprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ELIMINA_OCCORRENZE 1
extern  int * elimina_occorrenze_1();
extern  int * elimina_occorrenze_1_svc();
#define LISTA_FILE_CARATTERE 2
extern  OutputFileList * lista_file_carattere_1();
extern  OutputFileList * lista_file_carattere_1_svc();
extern int fileprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Input (XDR *, Input*);
extern  bool_t xdr_FileName (XDR *, FileName*);
extern  bool_t xdr_OutputFileList (XDR *, OutputFileList*);

#else /* K&R C */
extern bool_t xdr_Input ();
extern bool_t xdr_FileName ();
extern bool_t xdr_OutputFileList ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_XFILE_H_RPCGEN */
