/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_XFILE_H_RPCGEN
#define _RPC_XFILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define N 10
#define MAX_RIS 6

struct Prenotazione {
	char targa[8];
	char patente[6];
	char tipo[7];
	char immagini[13];
};
typedef struct Prenotazione Prenotazione;

struct Output {
	Prenotazione ris[MAX_RIS];
};
typedef struct Output Output;

struct Input {
	char targa[8];
	char patente[6];
};
typedef struct Input Input;

struct Tipo {
	char tipo[7];
};
typedef struct Tipo Tipo;

#define OPERATIONPROG 0x20000013
#define OPERATIONVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define VISUALIZZA_PRENOTAZIONI 1
extern  Output * visualizza_prenotazioni_1(Tipo *, CLIENT *);
extern  Output * visualizza_prenotazioni_1_svc(Tipo *, struct svc_req *);
#define AGGIORNA_LICENZA 2
extern  int * aggiorna_licenza_1(Input *, CLIENT *);
extern  int * aggiorna_licenza_1_svc(Input *, struct svc_req *);
extern int operationprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define VISUALIZZA_PRENOTAZIONI 1
extern  Output * visualizza_prenotazioni_1();
extern  Output * visualizza_prenotazioni_1_svc();
#define AGGIORNA_LICENZA 2
extern  int * aggiorna_licenza_1();
extern  int * aggiorna_licenza_1_svc();
extern int operationprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Prenotazione (XDR *, Prenotazione*);
extern  bool_t xdr_Output (XDR *, Output*);
extern  bool_t xdr_Input (XDR *, Input*);
extern  bool_t xdr_Tipo (XDR *, Tipo*);

#else /* K&R C */
extern bool_t xdr_Prenotazione ();
extern bool_t xdr_Output ();
extern bool_t xdr_Input ();
extern bool_t xdr_Tipo ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_XFILE_H_RPCGEN */
